# baseURL = "https://skdishansachin.com/"
locale = "en-us"
title = "Dishan Sachin"

[params]
  theme = "dark"
  siteName = "Dishan Sachin"
  dateLocale = "en-GB"
  description = "Just trying to understand how things work."

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      attributes = true
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = "dracula"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  # [[menu.main]]
  #   name = "About"
  #   url = "/about/"
  #   weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2 # 3

[taxonomies]

[outputs]
  home = ["html", "rss"]
  section = ["html", "rss"]

[minify]
  minifyOutput = true
